import { _format } from "~modules-core/utility/fomat";
import { TGridColDef } from "~types/data-grid";

export const transactionColumns: TGridColDef[] = [
    {
      field: "created",
      headerName: "Ngày tạo",
      minWidth: 75,
      type: "date",
      filterKey: "createdDate",
      sortAscValue: 12,
      sortDescValue: 0,
      renderCell: ({ row }) => _format.converseDate(row?.created),
    },
    {
      field: "partnerCode",
      headerName: "Mã đối tác",
      minWidth: 120,
      filterKey: "partnerCode",
      sortAscValue: 13,
      sortDescValue: 2,
    },
    {
      field: "partnerName",
      headerName: "Tên đối tác",
      minWidth: 150,
      flex: 1,
      filterKey: "partnerName",
      sortAscValue: 14,
      sortDescValue: 3,
    },
    {
      field: "explain",
      headerName: "Diễn giải",
      minWidth: 150,
      flex: 1,
      filterKey: "explain",
      sortAscValue: 15,
      sortDescValue: 4,
    },
    {
      field: "categoryName",
      headerName: "Danh mục",
      minWidth: 150,
      filterKey: "categoryTransaction",
      sortAscValue: 16,
      sortDescValue: 5,
    },
    {
      field: "billNumber",
      headerName: "Số hoá đơn",
      minWidth: 120,
      filterKey: "billNumber",
      sortAscValue: 17,
      sortDescValue: 6,
    },
    {
      field: "owe",
      headerName: "Nợ",
      minWidth: 100,
      flex: 1,
      filterKey: "owe",
      sortAscValue: 18,
      sortDescValue: 7,
      renderCell: ({ row }) => _format.getVND(row?.owe),
    },
    {
      field: "moneyCollect",
      headerName: "Tiền thu vào",
      minWidth: 150,
      flex: 1,
      filterKey: "moneyCollect",
      sortAscValue: 19,
      sortDescValue: 8,
      renderCell: ({ row }) => _format.getVND(row?.moneyCollect),
    },
    {
      field: "totalBalance",
      headerName: "Số dư tổng",
      minWidth: 150,
      flex: 1,
      filterKey: "moneyCollect",
      sortAscValue: 19,
      sortDescValue: 8,
      renderCell: ({ row }) => _format.getVND(row?.totalBalance),
    },
    {
      field: "accountBalance",
      headerName: "Số dư tài khoản",
      minWidth: 150,
      flex: 1,
      filterKey: "accountBalance",
      sortAscValue: 21,
      sortDescValue: 9,
      renderCell: ({ row }) => _format.getVND(row?.accountBalance),
    },
  ];